[project]
name = "learn-scala2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.6"
dependencies = [
    "jupyter>=1.1.1",
    "jupyterlab-git>=0.51.2",
]
